# Generated by Django 3.2.20 on 2025-09-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedentity',
            name='patient_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
