# Generated by Django 3.2.20 on 2025-10-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedentity',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
